# Script mode (cmake -P): embed files into a C++ source as byte arrays.
#
#   cmake -DOUT=<file.cpp> -DFILES=<a|b|...> -DNAMESPACE=<ns> -DFUNCTION=<fn> -P EmbedFiles.cmake
#
# Writes `std::span<const patch::embedded::File> <ns>::<fn>()` (declared in src/patch/embed.hpp):
# every file by its base name, sorted by name (byte order), with its exact bytes. The files stay
# the single source of truth; the generated source is rebuilt whenever one of them changes.

string(REPLACE "|" ";" files "${FILES}")
set(entries)
foreach(path IN LISTS files)
    get_filename_component(name "${path}" NAME)
    list(APPEND entries "${name}|${path}")
endforeach()
list(SORT entries)  # by name: the order the Python pipeline reads them in (a sorted glob)

set(body "// Generated by cmake/EmbedFiles.cmake: do not edit.\n#include \"patch/embed.hpp\"\n\nnamespace {\n\n")
set(table "")
set(index 0)
foreach(entry IN LISTS entries)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 name)
    list(GET parts 1 path)
    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # One trailing 0 keeps an empty file's array legal (the size leaves it out).
    string(APPEND body "const unsigned char kFile${index}[] = {${bytes}0};\n")
    string(APPEND table "    {\"${name}\", kFile${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()
if(index EQUAL 0)
    message(FATAL_ERROR "EmbedFiles: no files to embed")
endif()
string(APPEND body "\nconst patch::embedded::File kFiles[] = {\n${table}};\n\n}  // namespace\n\n")
string(APPEND body "namespace ${NAMESPACE} {\nstd::span<const File> ${FUNCTION}() { return kFiles; }\n}  // namespace ${NAMESPACE}\n")

# Rewrite only on change, so an unchanged catalog does not rebuild the library.
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
    if(old STREQUAL body)
        return()
    endif()
endif()
file(WRITE "${OUT}" "${body}")
